### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by ScarletMcLearn** [banglakit/spacy-models#1]
Does not work. Cannot install dependencies and make it run on kaggle. Sad.

**Comment by aniruddha-adhikary** [comment]
How have you tried using this? Could you elaborate for us to replicate the issue @ScarletMcLearn

**Comment by aniruddha-adhikary** [comment]
No reply from @ScarletMcLearn . Closing

**Comment by ScarletMcLearn** [comment]
Sorry. Working now.
Closed.
